# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python CI

# trigger the workflow
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # step 1: check out the 
    - name: check out code
      uses: actions/checkout@v2

    # step 2:set up python 
    - name: set up python 
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    # step 3:Install dependencies
    - name: Install dependencies
      run:
        python -m pip install --upgrade pip
        pip install -r requirement.txt

    # step 4:run test
    - name: run test
      run:
        pytest
